name: Lint

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  solidity:
    runs-on: ubuntu-latest

    steps:
      - name: Check out github repository
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
        with:
          fetch-depth: 1

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@c7450ba673e133f5ee30098b3b54f444d3a2ca2d # v1

      - name: Run Forge formatter check
        run: forge fmt --check
